services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  postgres:
    image: postgres:16
    # env_file:
    #   - ./backend/.env
    environment:
      POSTGRES_USER: ${{ vars.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_DB: ${{ vars.DB_NAME }}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    # env_file:
    #   - ./backend/.env
    environment:
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_USER: ${{ vars.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ vars.DB_NAME }}
      SERVER_ADDRESS: ${{ vars.SERVER_ADDRESS }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REDIS_ADDR: redis:6379
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-chat-app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
volumes:
  postgres_data:
